### ISSUE TITLE
Using with a solution file

### ISSUE THREAD

**Issue by pablinos** [LHCGreg/SlowMonkey#3]
I'm trying to get our VS solution building using mono/xbuild on my Mac. We're using SlowCheetah for the app.config transforms, so this seems like the natural replacement!

I installed the nuget package in the solution's packages folder. and then editted the .sln file to have:

``` xml
  <PropertyGroup Label="SlowMonkey">
    <SlowMonkeyTargetPath>$([System.IO.Path]::GetFullPath( $(MSBuildProjectDirectory)\..\packages\SlowMonkey.1.1.1\build))</SlowMonkeyTargetPath>
  </PropertyGroup>
  <Import Project="$(SlowMonkeyTargetPath)\SlowMonkey.targets" />
```

However, I then have to edit the SlowMonkey.targets file to have:

``` xml
  <PropertyGroup>
    <SlowMoneyTargetPath Condition=" '$(SlowMoneyTargetPath)'=='' ">$(MSBuildProjectDirectory)</SlowMoneyTargetPath>
  </PropertyGroup>
```

and edit the TransformXml task to be

``` xml
  <UsingTask TaskName="SlowMonkey.Tasks.TransformXml" AssemblyFile="$(SlowMonkeyTargetPath)\SlowMonkey.Tasks.dll" />
```

So, is this all really necessary? Am I using it in the correct way? If so, how do I formalise this change so it works for the general case?

**Comment by LHCGreg** [comment]
What version of mono will you be building with? If not something ancient like 2.10.8.1, installing the nuget package through the package manager should just work and automatically add the required XML to the .csproj file. You can then build with xbuild /p:Configuration=Release and it will pick up an app.Release.config transform file if present and use it. If you are using an old version of mono such as 2.10.8.1, you may have to edit the XML that nuget automatically adds to the .csproj and replace the import with something simpler like

<Import Project="..\packages\SlowMonkey.1.1.1\build\SlowMonkey.targets" />

You should not have to edit SlowMonkey.targets at all.

Which OS did you install the package on?

**Comment by pablinos** [comment]
Ah, sounds like I haven't installed the package properly then. Thought I could be doing something dumb! I just used nuget and ran:

```
nuget install SlowMonkey
```

Although that was in the solution directory not the project directory. I'm using Mono 4.01 and nuget 2.8.1

**Comment by pablinos** [comment]
I think I may have just answered my own question. That doesn't edit the .csproj files. It looks like you can only do that from the package manager in VS or Mono develop. Do you know anyway of doing it from the commandline on OS X or Linux?

**Comment by LHCGreg** [comment]
Sorry, I'm not very familiar with using nuget.exe directly to install packages. https://docs.nuget.org/consume/command-line-reference doesn't seem to have any options that would indicate a project to install the package to. If you must install the package using nuget.exe instead of VS or MonoDevelop, the Nuget team may be able to tell how you to install a package to a project file.

**Comment by pablinos** [comment]
Yep, it looks more like how I'm using it. I might ask the OmniSharp people too, as they create lots of tools for using whichever editor you choose - that's essentially what I'm trying to do!
